### PR TITLE
Documentation via MkDocs

### PR DESCRIPTION
**Pull request by LukasManinger**
I created a package documentation site using MkDocs (Material) that can be hosted on GitHub Pages. An approximate live demonstration can be viewed [here](https://lukasmaninger.github.io/lqg/). After merging these changes, you will need to select `gh-pages` as source branch for deployment under "Settings">"Pages".

Apart from the documentation, I updated the tutorial notebooks by replacing Jupyter widgets with interactive Altair charts that can be viewed on static websites. I left the old notebooks under `notebooks/` untouched and placed the adjusted versions at `docs/tutorials/`. You might want to delete the old ones later to avoid confusion.

### CODE REVIEW

**Comment by dominikstrb** [comment]
Thank you, this is great!

Maybe I missed this: is there a reason why we need the icon, which is not rendering, in [the beginning of the readme](https://github.com/dominikstrb/lqg/blob/main/docs/README.md?plain=1#L1-L3)?

**Comment by LukasManinger** [comment]
Thanks for merging! For the sake of completeness, I want to reply anyway.

The YAML frontmatter is used by MkDocs to specify the icon in the navigation bar:
Screenshot

However, GitHub displays the frontmatter as a table with plain text. I agree with you that this is a bit irritating. For now, I came up with the following solution: I deleted the YAML frontmatter from the README file and add it again during the deployment workflow (see [these two lines](https://github.com/LukasManinger/lqg/blob/d69c94a1377db64cf93d3a250c7caf4bb86fe307/.github/workflows/ci.yml#L19-L20)). It's a bit hacky but it seems to work and I currently have no better idea.

**Comment by LukasManinger** [comment]
I forgot to mention: As soon as the website is up, you need to adjust the URL to which the "documentation" batch in the README is linking.

```diff
- [![Static Badge](https://img.shields.io/badge/documentation-546d78)](https://lukasmaninger.github.io/lqg/)
+ [![Static Badge](https://img.shields.io/badge/documentation-546d78)](https://rothkopflab.github.io/lqg/)
```

I forgot to do this, but maybe the current state is better than a dead link after all.

**Comment by dominikstrb** [comment]
Sounds good, thanks!

**Pull request merged**
